FROM golang:1.26-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /replica ./cmd/replica

FROM alpine:latest
WORKDIR /app
COPY --from=builder /replica /app/replica
EXPOSE 9001
ENTRYPOINT ["/app/replica"]